# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install global dependencies
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running scripts
RUN pnpm install --ignore-scripts

# Copy source code
COPY . .

# Build the project
RUN pnpm build

# Define the startup command
CMD ["node", "dist/cli.js", "start"]
